### PR TITLE
Add Traefik CORS Example

### PR DESCRIPTION
**Pull request by arcoast**
Thanks for making this, it's great having a self hosted Invidious instance but it's certainly not the prettiest so love this project, but as I use Traefik I noticed there wasn't an example to enable me to easily get it working.  Using your nginx example have managed to get it all working with Traefik v2.11.0, so thought I'd submit a PR to the docs.

### CODE REVIEW

**Comment by WardPearce** [comment]
Awesome, this that working on your instance?  Not sure how Traefik handles preflight checks for CORS.

**Comment by arcoast** [comment]
Yeah, seems to be all working matey, without this middleware I was getting exactly the same errors as in this [report](https://github.com/WardPearce/Materialious/issues/16).  

Once I added the middleware I'm able to see my subscriptions (I'm already logged in on Invidious), play videos, get trending, haven't played around with playlists yet though.

**Comment by arcoast** [comment]
Just created, deleted, edited some playlists and checked I can get history.  All seems OK to me.  

I'm not a dev, so feel free to leave it open if you want someone with a few more brain cells to give it a once over first, I don't mind and won't be offended! I'll report back on here or matrix if I find any issues. :+1: 

It's visually beautiful, (told my mate about it, he's installing it tomorrow!) :smile:

**Comment by WardPearce** [comment]
Nah I'm happy to push, if its working for you it should be fine :+1: worse case someone can open a issue about it

**Pull request merged**
